### ISSUE TITLE
Pre-Roll And Normal Ads Coming Through Again As Of April 1st

### ISSUE THREAD

**Issue by SwoOpLo0pz** [arthurbolsoni/Purple-adblock#38] opened 2022-04-01 22:22 UTC
I do remember recently accepting new permissions or something for this plugin to make it start working again. It's been an absolutely incredible piece of work that functions perfectly. Just making it known ads have started to come through

**Comment by TFirst99** [comment] 2022-04-01 22:40
Confirmed here, I am seeing pre-rolls and normal ads

**Comment by marcusnewton** [comment] 2022-04-03 12:02
Also confirming this has begun happening again

**Comment by Mawxy** [comment] 2022-04-03 15:21
Confirmed

`Opening: chesscomlive
server off
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/chesscomlive.m3u8?allow_source=true&fast_bread=true&p=9456643&play_session_id=e24086f0b0486464dbcd274ea48106cf&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=c9a9651c29e44a55bd2cbac5d20aab1c2051171c&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22chesscomlive%22%2C%22channel_id%22%3A186705600%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22twitch-web-wall-mason%22%2C%22expires%22%3A1648997457%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22embed%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A137129058%2C%22user_ip%22%3A%22107.5.153.38%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.9.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/chess.m3u8?allow_source=true&fast_bread=true&p=4496859&play_session_id=a8c9d64d609423184e0d3910dbcadc96&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=eb5598f03739f1bab9c67cb019d1dc5db5290d43&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22chess%22%2C%22channel_id%22%3A7601562%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%22archives%22%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22twitch-web-wall-mason%22%2C%22expires%22%3A1648997462%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22embed%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A137129058%2C%22user_ip%22%3A%22107.5.153.38%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.9.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/chesscomlive.m3u8?allow_source=true&fast_bread=true&p=1232230&play_session_id=08597423d7357c0cfcf3141cc9e41ed3&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=979e572b4d635c76543cc4cec1444cc86800a682&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22chesscomlive%22%2C%22channel_id%22%3A186705600%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22twitch-web-wall-mason%22%2C%22expires%22%3A1648997495%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22embed%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A137129058%2C%22user_ip%22%3A%22107.5.153.38%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.9.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/phedran.m3u8?allow_source=true&fast_bread=true&p=6762685&play_session_id=036b485a3e8bdc44d18e22a17734a9cd&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=470f852dc29c2fc236c9aad19670853d528acd36&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22phedran%22%2C%22channel_id%22%3A31611456%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22twitch-web-wall-mason%22%2C%22expires%22%3A1649000432%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22frontpage%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A137129058%2C%22user_ip%22%3A%22107.5.153.38%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.9.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/photochess.m3u8?allow_source=true&fast_bread=true&p=2834489&play_session_id=0392bcac781ca034c1b01f21e0109ad8&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=8a3eccbede46bafcac022b3ea567f2c16735ee5e&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22photochess%22%2C%22channel_id%22%3A154972160%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%22archives%22%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22twitch-web-wall-mason%22%2C%22expires%22%3A1649000436%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A137129058%2C%22user_ip%22%3A%22107.5.153.38%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.9.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/photochess.m3u8?allow_source=true&fast_bread=true&p=7318242&play_session_id=3386e11b8c8d7614aeee4b713744c0d3&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=91e9d8ec15820c8960f7dfdb1f0d8879665b77c7&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22photochess%22%2C%22channel_id%22%3A154972160%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%22archives%22%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22twitch-web-wall-mason%22%2C%22expires%22%3A1649000441%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A137129058%2C%22user_ip%22%3A%22107.5.153.38%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.9.0`

**Comment by EPuncker** [comment] 2022-04-03 15:24
it works for me when I use the `Tunnel and Local requests - BETA` option, but not for every channel, some channels become unwatchable, just a black screen player

**Comment by AEHamrick** [comment] 2022-04-13 21:25
Confirmed with "only user tunnel" option -- trying with "tunnel and local requests" and will update

**Comment by arthurbolsoni** [comment] 2022-04-13 21:26
i did server update to another server, just reopen the browser to restart the extension.

**Comment by marcusnewton** [comment] 2022-04-14 00:45
> i did server update to another server, just reopen the browser to restart the extension.

Was it just the server you were using going down or is T***h actively trying to make the extension stop working?

**Comment by arthurbolsoni** [comment] 2022-04-14 00:49
the "dude" in russia started a war with his neighbor. so this limited payment methods with russia servers, it made me have to change the server proxy.

**Comment by AEHamrick** [comment] 2022-04-14 01:07
Thanks @arthurbolsoni , seems to be all good now after reloading the browser

**Comment by Kam7r** [comment] 2022-04-29 05:15
Hi, iam sorry if my questions seems stupid because, 1st of all , i'm not a dev' or anything, just a hardware guy, but i really like your work, so :  I have a server at home ( a physical one with a 1gb/s connexion reserved only to it ), so i wanted to know since you seems to have problems with the server and more you have to pay for it... if it is possible to make my server do the work for me through my local network with a script or something? i mean like a personnal VPN with wireguard for example ?  maybe decentralizing servers like ppl like me who have a little one could make the load lighter ? 
again sorry if i'm seems clueless and for my broken english .

**Comment by arthurbolsoni** [comment] 2022-04-29 06:05
> Hi, iam sorry if my questions seems stupid because, 1st of all , i'm not a dev' or anything, just a hardware guy, but i really like your work, so : I have a server at home ( a physical one with a 1gb/s connexion reserved only to it ), so i wanted to know since you seems to have problems with the server and more you have to pay for it... if it is possible to make my server do the work for me through my local network with a script or something? i mean like a personnal VPN with wireguard for example ? maybe decentralizing servers like ppl like me who have a little one could make the load lighter ? again sorry if i'm seems clueless and for my broken english .

I really appreciate your desire to help. but there is a very important point in setting up the server, which is the location. internally the server makes 3 requests to twitch, these 3 requests need to be with an ip of countries where twitch is not present with ads. these servers are not expensive compared to the donation I've been getting (basically enough to keep for 5 years and more). the errors seem to come from a massive request of only 1 ip makes twitch retreat and the server crashes (error in the server code) I'm considering using 2 servers with different ips. where the extension does the low balance. but first I need to finish the dev branch version of the extension

**Comment by Kam7r** [comment] 2022-04-30 23:14
ok i understand, i'm glad at least it cost you "nothing" , again big thx for your work

**Comment by Rhia-mon** [comment] 2022-05-21 19:06
Heya, I started to use the ext a little while ago and for a while it worked  just fine.  Yesterday, I started getting ads again, on most of the channels that I watch.  Not so much the ads that play when you first start watching. Mostly just the one's that happen while watching. I'm in Australia. Thank you for the work you put into this. =)

**Closed** 2022-08-30 13:13 UTC
